"""Emit pieces.ts from a solutions15-style entry (all 10 digits designed)."""

import json
import sys

src = sys.argv[1]
idx = int(sys.argv[2]) if len(sys.argv) > 2 else 0
out_path = sys.argv[3] if len(sys.argv) > 3 else \
    "/Users/zaki/Projects/zakigg/.claude/worktrees/web-puzzle-builder-54eb96/src/lib/puzzle/pieces.ts"

entry = json.load(open(src))[idx]

DIGIT_ORDER = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]


def parse(cm):
    return {tuple(int(v) for v in k.split(",")): m for k, m in cm.items()}


board = {}
for d, sol in entry["solution"].items():
    for c, m in parse(sol["cells"]).items():
        if board.get(c, 0) & m:
            print("OVERLAP at", c, d, file=sys.stderr)
            sys.exit(1)
        board[c] = board.get(c, 0) | m
area = sum(bin(m).count("1") for m in board.values()) / 4.0
print(f"board union area: {area} (notches: {79 - area})", file=sys.stderr)
print("variants:", entry["variants"], file=sys.stderr)


def cells_list(cm):
    return [[x, y, m] for (x, y), m in sorted(cm.items())]


lines = []
lines.append("// Generated by scripts/puzzle-design/gen_pieces4.py — do not edit by hand.")
lines.append("// Geometry verified: exact tiling found by multi-variant exact cover.")
lines.append("import type { Cell, Pose } from './geometry';")
lines.append("")
lines.append("export interface PieceDef {")
lines.append("\tid: string;")
lines.append("\tcells: Cell[];")
lines.append("\t/** Reference solution pose (board coordinates). */")
lines.append("\thome: Pose;")
lines.append("}")
lines.append("")
lines.append("export const BOARD_W = 11;")
lines.append("export const BOARD_H = 9;")
lines.append("")
lines.append("/** Target silhouette: union of the reference solution. */")
lines.append("export const BOARD_CELLS: Cell[] = [")
for c in cells_list(board):
    lines.append(f"\t{json.dumps(c)},")
lines.append("];")
lines.append("")
lines.append("export const PIECES: PieceDef[] = [")
for d in DIGIT_ORDER:
    cells = cells_list(parse(entry["cells"][d]))
    sol = entry["solution"][d]
    lines.append("\t{")
    lines.append(f"\t\tid: '{d}',")
    lines.append(f"\t\tcells: {json.dumps(cells)},")
    lines.append(
        f"\t\thome: {{ x: {sol['ox']}, y: {sol['oy']}, rot: {sol['rot']}, flip: {str(bool(sol['flip'])).lower()} }}")
    lines.append("\t},")
lines.append("];")
lines.append("")

open(out_path, "w").write("\n".join(lines))
print(f"wrote {out_path}", file=sys.stderr)
