"""Build pieces.ts from a solve10 hit: 7 fixed digits + 3 leftover pieces.

Usage: gen_pieces2.py <hits_json> <hit_index> <label1,label2,label3> [out_path]
Labels assign digits to the leftover components sorted by (area, x) —
e.g. "1,7,4" maps smallest->1 etc. Component order printed for inspection.
"""

import json
import sys

import solve7 as S

N_, E_, S_, W_ = 1, 2, 4, 8
VALID = {3, 6, 9, 12, 15}

src = sys.argv[1]
idx = int(sys.argv[2])
labels = sys.argv[3].split(",") if len(sys.argv) > 3 else ["1", "7", "4"]
import os
out_path = sys.argv[4] if len(sys.argv) > 4 else os.path.join(
    os.path.dirname(__file__), "..", "..", "src", "lib", "puzzle", "pieces.ts")

entry = json.load(open(src))[idx]


def parse(cm):
    return {tuple(int(v) for v in k.split(",")): m for k, m in cm.items()}


def req_at(c):
    return (S.REQUIRED >> S.BIT[c]) & 15


def trim(comp):
    """drop optional quarters so every cell is a legal shape; None if impossible."""
    out = {}
    for c, m in comp.items():
        req = m & req_at(c)
        if m in VALID:
            out[c] = m
            continue
        # try dropping optional quarters: choose the largest legal subset of m
        # that still contains req
        best = None
        for target in (15, 3, 6, 9, 12):
            if (target & m) == target and (req & target) == req and (req or target != 15):
                if best is None or bin(target).count("1") > bin(best).count("1"):
                    best = target
        if best is None:
            if req == 0:
                continue  # pure-optional sliver: drop entirely
            return None
        if best:
            out[c] = best
    # drop stray zero cells
    return {c: m for c, m in out.items() if m}


fixed = {d: parse(v["cells"]) for d, v in entry["fixed"].items()}
fixed_meta = {d: v for d, v in entry["fixed"].items()}
leftovers = [parse(cm) for cm in entry["leftovers"]]

trimmed = []
for comp in leftovers:
    t = trim(comp)
    if t is None:
        print("ILLEGAL leftover — pick another hit", file=sys.stderr)
        sys.exit(1)
    trimmed.append(t)

# sort components (area, then min x) and pair with labels
def area(cm):
    return sum(bin(m).count("1") for m in cm.values()) / 4.0


order = sorted(range(len(trimmed)), key=lambda i: (area(trimmed[i]), min(x for x, y in trimmed[i])))
wild = {}
for lab, i in zip(labels, order):
    wild[lab] = trimmed[i]
    print(f"leftover {i} -> '{lab}' area={area(trimmed[i])}", file=sys.stderr)

# overlap / coverage sanity
union = {}
for name, cm in list(fixed.items()) + list(wild.items()):
    for c, m in cm.items():
        if union.get(c, 0) & m:
            print("OVERLAP at", c, name, file=sys.stderr)
            sys.exit(1)
        union[c] = union.get(c, 0) | m
for c in S.FILLED:
    req = req_at(c)
    if (union.get(c, 0) & req) != req:
        print("UNCOVERED required at", c, file=sys.stderr)
        sys.exit(1)
print(f"board union area: {sum(bin(m).count('1') for m in union.values()) / 4.0}", file=sys.stderr)


def normalize(cm):
    mnx = min(x for x, y in cm)
    mny = min(y for x, y in cm)
    return {(x - mnx, y - mny): m for (x, y), m in cm.items()}, mnx, mny


DIGIT_ORDER = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
pieces = {}
for d, meta in fixed_meta.items():
    base = None
    # reconstruct base cells: inverse of transform(rot, flip) applied to placed cells
    placed = parse(meta["cells"])
    local = {(x - meta["ox"], y - meta["oy"]): m for (x, y), m in placed.items()}
    # invert rotation then flip (transform: flip first, then rot)
    inv = local
    ROT_CCW = {N_: W_, W_: S_, S_: E_, E_: N_}
    for _ in range(meta["rot"] % 4):
        inv = {(-y, x): S.qmap(m, ROT_CCW) for (x, y), m in inv.items()}
        mnx = min(x for x, y in inv)
        mny = min(y for x, y in inv)
        inv = {(x - mnx, y - mny): m for (x, y), m in inv.items()}
    if meta["flip"]:
        FLIP_Q = {N_: N_, S_: S_, E_: W_, W_: E_}
        inv = {(-x, y): S.qmap(m, FLIP_Q) for (x, y), m in inv.items()}
        mnx = min(x for x, y in inv)
        mny = min(y for x, y in inv)
        inv = {(x - mnx, y - mny): m for (x, y), m in inv.items()}
    # sanity: re-apply transform must reproduce local
    chk = S.transform(inv, meta["rot"], meta["flip"])
    assert chk == {(x, y): m for (x, y), m in normalize(local)[0].items()}, f"roundtrip failed for {d}"
    pieces[d] = {"cells": inv, "home": {"x": meta["ox"], "y": meta["oy"],
                                        "rot": meta["rot"], "flip": bool(meta["flip"])}}

for lab, cm in wild.items():
    n, mnx, mny = normalize(cm)
    pieces[lab] = {"cells": n, "home": {"x": mnx, "y": mny, "rot": 0, "flip": False}}


def cells_list(cm):
    return [[x, y, m] for (x, y), m in sorted(cm.items())]


lines = []
lines.append("// Generated by scratchpad/gen_pieces2.py — do not edit by hand.")
lines.append("// Geometry verified: exact tiling found by guided search (docs/puzzle.md).")
lines.append("import type { Cell, Pose } from './geometry';")
lines.append("")
lines.append("export interface PieceDef {")
lines.append("\tid: string;")
lines.append("\tcells: Cell[];")
lines.append("\t/** Reference solution pose (board coordinates). */")
lines.append("\thome: Pose;")
lines.append("}")
lines.append("")
lines.append("export const BOARD_W = 11;")
lines.append("export const BOARD_H = 9;")
lines.append("")
lines.append("/** Target silhouette: union of the reference solution. */")
lines.append("export const BOARD_CELLS: Cell[] = [")
for c in cells_list(union):
    lines.append(f"\t{json.dumps(c)},")
lines.append("];")
lines.append("")
lines.append("export const PIECES: PieceDef[] = [")
for d in DIGIT_ORDER:
    p = pieces[d]
    h = p["home"]
    lines.append("\t{")
    lines.append(f"\t\tid: '{d}',")
    lines.append(f"\t\tcells: {json.dumps(cells_list(p['cells']))},")
    lines.append(f"\t\thome: {{ x: {h['x']}, y: {h['y']}, rot: {h['rot']}, flip: {str(h['flip']).lower()} }}")
    lines.append("\t},")
lines.append("];")
lines.append("")

open(out_path, "w").write("\n".join(lines))
print(f"wrote {out_path}", file=sys.stderr)
